### plot 3: plot all temperatures, one plot
RPlot3 <- function (data) { 
  ## needs ATHR1, ATHR2, AT_A
  par(oma=c(1.1,0,0,0))
  ylb <- expression (paste ("temperature  ATy  [", degree, "C]"))
  plotWAC (data[, c("Time", "ATHR2", "ATHR1", "AT_A")],
           ylab=ylb, lty=c(1,1,2,1), 
           lwd=c(2,1.5,1,2), legend.position=NA) # pulling legend out of plotWAC to increase font size
  legend('bottomright',c("ATHR2", "ATHR1", "AT_A"),col=c("blue","darkgreen","red"),text.col=c("blue","darkgreen","red"),lty=c(1,1,2),lwd=c(2,1.5,1))
  title(sprintf("Means L1-L2: %.2f; L2-_A: %.2f", 
                mean (data$ATHR1-data$ATHR2, na.rm=TRUE), 
                mean (data$ATHR2-data$AT_A, na.rm=TRUE)), cex.main=0.8)
  mtext(paste(FigFooter,'generated by RPlot3',FigDatestr),1,outer=T,cex=0.75)
}
